/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoresRouteImport } from './routes/cores'
import { Route as TipografiaRouteImport } from './routes/tipografia'
import { Route as ComponentesIndexRouteImport } from './routes/componentes/index'
import { Route as ComponentesBotaoRouteImport } from './routes/componentes/botao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoresRoute = CoresRouteImport.update({
  id: '/cores',
  path: '/cores',
  getParentRoute: () => rootRouteImport,
} as any)
const TipografiaRoute = TipografiaRouteImport.update({
  id: '/tipografia',
  path: '/tipografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesIndexRoute = ComponentesIndexRouteImport.update({
  id: '/componentes/',
  path: '/componentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesBotaoRoute = ComponentesBotaoRouteImport.update({
  id: '/componentes/botao',
  path: '/componentes/botao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cores': typeof CoresRoute
  '/tipografia': typeof TipografiaRoute
  '/componentes/botao': typeof ComponentesBotaoRoute
  '/componentes/': typeof ComponentesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cores': typeof CoresRoute
  '/tipografia': typeof TipografiaRoute
  '/componentes/botao': typeof ComponentesBotaoRoute
  '/componentes': typeof ComponentesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cores': typeof CoresRoute
  '/tipografia': typeof TipografiaRoute
  '/componentes/botao': typeof ComponentesBotaoRoute
  '/componentes/': typeof ComponentesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/cores' | '/tipografia' | '/componentes/botao' | '/componentes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cores' | '/tipografia' | '/componentes/botao' | '/componentes'
  id:
    | '__root__'
    | '/'
    | '/cores'
    | '/tipografia'
    | '/componentes/botao'
    | '/componentes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoresRoute: typeof CoresRoute
  TipografiaRoute: typeof TipografiaRoute
  ComponentesBotaoRoute: typeof ComponentesBotaoRoute
  ComponentesIndexRoute: typeof ComponentesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cores': {
      id: '/cores'
      path: '/cores'
      fullPath: '/cores'
      preLoaderRoute: typeof CoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tipografia': {
      id: '/tipografia'
      path: '/tipografia'
      fullPath: '/tipografia'
      preLoaderRoute: typeof TipografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes/': {
      id: '/componentes/'
      path: '/componentes'
      fullPath: '/componentes/'
      preLoaderRoute: typeof ComponentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes/botao': {
      id: '/componentes/botao'
      path: '/componentes/botao'
      fullPath: '/componentes/botao'
      preLoaderRoute: typeof ComponentesBotaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoresRoute: CoresRoute,
  TipografiaRoute: TipografiaRoute,
  ComponentesBotaoRoute: ComponentesBotaoRoute,
  ComponentesIndexRoute: ComponentesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
